os: Visual Studio 2017

clone_depth: 1

cache:
    - C:\.hunter -> .appveyor.yml

environment:
    BOOST_ROOT: C:\Libraries\boost_1_66_0
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_66_0\lib64-msvc-14.1
    PATH: "%PATH%;%BOOST_ROOT%;%BOOST_LIBRARYDIR%"

install:
    - git submodule update --init --recursive

build_script:
    - md build
    - cd build
    - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE=cmake/polly/vs-15-2017-win64.cmake ..
    - cmake --build . --config Release
