sudo: true
language: cpp

env:
    - CXXFLAGS="-std=gnu++11"

matrix:
    include:
      addons:
        apt:
            sources:
            - ubuntu-toolchain-r-test
            packages:
            - g++-4.9
      env:
      - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade autoconf automake berkeley-db4 libtool miniupnpc openssl protobuf; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install build-essential cmake gcc-4.9 g++-4.9 python-dev -y; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC=clang CXX=clang++; fi

script:
    - mkdir build && cd build
    - cmake ..
    - cmake --build . --config Release

os:
    - osx
