language: cpp

matrix:
    include:
        - os: linux
          dist: xenial
          sudo: required
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_TOOLCHAIN_FILE_NAME=gcc-cxx14-c11.cmake
        - os: osx
          osx_image: xcode10.1
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_TOOLCHAIN_FILE_NAME=clang-cxx14.cmake

addons:
    apt: # Linux
        packages:
            - build-essential
            - cmake
            - git
        sources:
          - ubuntu-toolchain-r-test
    homebrew: # macOS
        packages:
            - cmake
            - git

cache:
    directories:
        - $HOME/.hunter

script:
    - mkdir ./build
    - cd ./build
    - cmake -G "$CMAKE_GENERATOR_NAME" -DCMAKE_TOOLCHAIN_FILE=cmake/polly/$CMAKE_TOOLCHAIN_FILE_NAME ..
    - cmake --build . --config Release
