language: cpp

matrix:
    include:
        - name: "Android, Debug"
          os: linux
          dist: xenial
          sudo: required
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Debug"
              - CMAKE_TOOLCHAIN_FILE_NAME=android-ndk-r18b-api-21-x86-clang-libcxx.cmake
        - name: "Android, Release"
          os: linux
          dist: xenial
          sudo: required
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Release"
              - CMAKE_TOOLCHAIN_FILE_NAME=android-ndk-r18b-api-21-x86-clang-libcxx.cmake
        - name: "Linux, Debug"
          os: linux
          dist: xenial
          sudo: required
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Debug"
              - CMAKE_TOOLCHAIN_FILE_NAME=gcc-cxx14-c11.cmake
        - name: "Linux, Release"
          os: linux
          dist: xenial
          sudo: required
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Release"
              - CMAKE_TOOLCHAIN_FILE_NAME=gcc-cxx14-c11.cmake
        - name: "macOS, Debug"
          os: osx
          osx_image: xcode10.2
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Debug"
              - CMAKE_TOOLCHAIN_FILE_NAME=clang-cxx14.cmake
        - name: "macOS, Release"
          os: osx
          osx_image: xcode10.2
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Release"
              - CMAKE_TOOLCHAIN_FILE_NAME=clang-cxx14.cmake
              - CTEST_REGEXP="Tests$"

addons:
    apt: # Linux
        packages:
            - build-essential
            - cmake
            - git
            - unzip
            - wget
            - lcov
            - rpm
        sources:
            - ubuntu-toolchain-r-test
    homebrew: # macOS
        packages:
            - cmake
            - git
            - lcov

cache:
    directories:
        - $HOME/.hunter

before_install:
    - |
        if [ "$CMAKE_TOOLCHAIN_FILE_NAME" = "android-ndk-r18b-api-21-x86-clang-libcxx.cmake" ]; then
            echo "Installing Android NDK..."
            mkdir -p "$HOME/.android"
            wget -O "$HOME/.android/android-ndk-r18b-linux-x86_64.zip" "https://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip"
            unzip -qq "$HOME/.android/android-ndk-r18b-linux-x86_64.zip" -d "$HOME/.android"
            export ANDROID_NDK_r18b="$HOME/.android/android-ndk-r18b"
            ls -la "$ANDROID_NDK_r18b"
        fi

script:
    - mkdir ./build && cd ./build
    - >
        cmake -G "$CMAKE_GENERATOR_NAME"
        -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
        -DCMAKE_TOOLCHAIN_FILE=cmake/polly/$CMAKE_TOOLCHAIN_FILE_NAME
        -DBUILD_ALL:BOOL=TRUE
        ..
    - cmake --build . --config $CMAKE_BUILD_TYPE -- -j 2
    - cpack -C $CMAKE_BUILD_TYPE

deploy:
    provider: releases # GitHub Releases
    api_key:
        secure: "hRqB7OCjXxa91Jh6gvUgAevHfkR7e1Or/2kFVbKzI+BXCCrqdlV/G940/lcXu80qKzvtqD1usH0RGqhRLSGWTOmJixeZ1/zSNKp1c88OT1YcMyCGhHAx+68BPQp6yaGoKnkZncf+Ge9qkuIoboX8ayFRVeRnBbnf/VhNS/AHXrQZExAkY4UKCTSmKrUb8vmSsGlgFJ9VgCVEprlzUM9qIvZDcXf2f5mMOLgPS5M1h28mIFxjjqn2BBEvGnItf3sihloR51EN5DGCHdjeLWJv6pUoT67cElJJ1aOKECPSnfaIKLILOXMlckBUYcNT3EO9Fs8nfT+hMN/vqr8xFkNfY45UuCgkbute8/GPkfT2R3JsoeJ1df9z1yu8zpYYAvhPettilWIrjtPyg7ekXy2c8+Lzaut/iogokVCwZXy5yGAozU7RUYyLZvB+iZT/L4e4TnrkRM9Y9T2lSefrBql273wuc/X1n7pf3mMsalmMNwnEEyleCHE8KeJGzeFjdQu1Srmu41E61PIPBiHPsF9VQuFWXuVj6usqY/zvxJnoa4o/4uJ3NMWHFxCAiPmH559ElXwFAifN5LZ/6Dxu40MYjSkeDqJRT4uvhtVgCC73VWFRWgKAZjepP6tpohO/Xcab+00LFbYdHvDyK5LlABLwJFAix8prDJvyCKisq8+Rd24="
    file: dist/qwertycoin-*
    file_glob: true
    draft: true
    on:
        branch: master
        tags: true
        condition: $CMAKE_BUILD_TYPE = "Release"
    skip_cleanup: true