sudo: true
language: cpp
compiler: gcc
    
env:
    - CXXFLAGS="-std=gnu++11"

matrix:
    include:
    - os: linux
      addons:
        apt:
            sources:
            - ubuntu-toolchain-r-test
            packages:
            - g++-4.9
            - libboost1.55-all-dev
      env:
      - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9
    - os: osx

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade autoconf automake berkeley-db4 libtool miniupnpc openssl protobuf; fi
    
script:
    - mkdir build && cd build
    - cmake .. && make
