language: cpp

matrix:
    include:
        - os: linux
          dist: xenial
          sudo: required
        - os: osx
          osx_image: xcode10.1

addons:
    apt: # Linux
        packages:
            - build-essential
            - cmake
            - git
        sources:
          - ubuntu-toolchain-r-test
    homebrew: # macOS
        packages:
            - cmake
            - git

cache:
    directories:
        - $HOME/.hunter

script:
    - mkdir ./build && cd ./build
    - cmake ..
    - cmake --build . --config Release --target SimpleWallet -- -j4
